### ISSUE TITLE
Migrate Test user + Vaults over to new 1password account.

### ISSUE THREAD

**Issue by MattKiazyk** [RobotsAndPencils/1password-action#53]
We've been accepted for using 1password for free. https://robotsandpencils-1passwordaction.1password.com/

- [x] Create a new vault
- [x] Create a user CI user
- [x] Add same items in the vault for CI to use
- [x] Update Github secrets
- [x] Update CI test to use 
- [x] 🍺

**Comment by interstateone** [comment]
✅ https://github.com/RobotsAndPencils/1password-action/actions/runs/532507535
